apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: scala-seed-project
build:
  tagPolicy:
    gitCommit: { }
  artifacts:
    - image: docker.io/library/scala-seed-project-flyway
      docker:
        dockerfile: flyway/Dockerfile
    - image: docker.io/library/scala-seed-project
      custom:
        dependencies:
          paths:
            - "src/main" # this is the source directory that will be watched for changes
        buildCommand: |
          ./src/main/script/buildApplicationImage.sh

deploy:
  helm:
    releases:
      - name: scala-seed-project
        chartPath: scala-seed-project
        setValueTemplates:
          project.rootdir: "{{.PWD}}"
