apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Values.image.repository_name }}
spec:
  selector:
    app: {{ .Values.image.repository_name }}
  ports:
    - name: service-port
      port: 9000
      targetPort: app-port
    - name: debug-port
      port: 5005